import type { ChampionTag } from "./types";

export const championTags: Record<string, ChampionTag[]> = {
  Aatrox: ["frontline", "sustain", "ad"],
  Ahri: ["ap", "burst", "mobile"],
  Akali: ["ap", "assassin", "burst", "mobile"],
  Akshan: ["ad", "assassin", "mobile"],
  Alistar: ["tank", "frontline", "heavy_cc", "support"],
  Ambessa: ["frontline", "ad", "burst", "mobile"],
  Amumu: ["tank", "frontline", "heavy_cc", "ap"],
  Anivia: ["ap", "heavy_cc", "poke"],
  Annie: ["ap", "burst", "heavy_cc"],
  Aphelios: ["ad"],
  Ashe: ["ad", "heavy_cc", "poke"],
  "Aurelion Sol": ["ap", "burst", "poke"],
  Aurora: ["ap", "burst", "mobile"],
  Azir: ["ap", "poke"],
  Bard: ["support", "healing", "heavy_cc", "mobile"],
  "Bel'Veth": ["ad", "sustain", "mobile"],
  Blitzcrank: ["tank", "heavy_cc", "support"],
  Brand: ["ap", "burst", "poke"],
  Braum: ["tank", "frontline", "heavy_cc", "support"],
  Briar: ["frontline", "sustain", "ad", "mobile"],
  Caitlyn: ["ad", "poke"],
  Camille: ["frontline", "ad", "burst", "mobile"],
  Cassiopeia: ["ap", "sustain"],
  "Cho'Gath": ["tank", "frontline", "high_hp", "heavy_cc", "ap"],
  Corki: ["ad", "ap", "poke", "mobile"],
  Darius: ["frontline", "high_hp", "ad"],
  Diana: ["ap", "assassin", "burst"],
  Draven: ["ad", "burst"],
  "Dr. Mundo": ["tank", "frontline", "high_hp", "sustain"],
  Ekko: ["ap", "assassin", "burst", "mobile"],
  Elise: ["ap", "assassin", "burst", "heavy_cc", "mobile"],
  Evelynn: ["ap", "assassin", "burst", "mobile"],
  Ezreal: ["ad", "poke", "mobile"],
  Fiddlesticks: ["ap", "heavy_cc", "sustain"],
  Fiora: ["ad", "sustain", "mobile"],
  Fizz: ["ap", "assassin", "burst", "mobile"],
  Galio: ["tank", "frontline", "heavy_cc", "ap"],
  Gangplank: ["ad", "burst", "poke"],
  Garen: ["tank", "frontline", "high_hp", "ad"],
  Gnar: ["tank", "frontline", "heavy_cc", "ad", "poke"],
  Gragas: ["tank", "frontline", "heavy_cc", "ap", "sustain"],
  Graves: ["ad", "burst", "mobile"],
  Gwen: ["ap", "sustain", "mobile"],
  Hecarim: ["frontline", "heavy_cc", "ad", "mobile"],
  Heimerdinger: ["ap", "poke"],
  Hwei: ["ap", "burst", "heavy_cc", "poke"],
  Illaoi: ["frontline", "high_hp", "sustain", "ad"],
  Irelia: ["ad", "sustain", "mobile"],
  Ivern: ["support", "shielding", "heavy_cc"],
  Janna: ["support", "shielding", "healing", "heavy_cc"],
  "Jarvan IV": ["frontline", "heavy_cc", "ad", "mobile"],
  Jax: ["frontline", "ad", "sustain", "mobile"],
  Jayce: ["ad", "burst", "poke", "mobile"],
  Jhin: ["ad", "poke", "heavy_cc"],
  Jinx: ["ad"],
  "Kai'Sa": ["ad", "ap", "burst", "mobile"],
  Kalista: ["ad", "mobile"],
  Karma: ["support", "shielding", "poke", "ap"],
  Karthus: ["ap", "poke"],
  Kassadin: ["ap", "assassin", "burst", "mobile"],
  Katarina: ["ap", "assassin", "burst", "mobile"],
  Kayle: ["ap", "ad", "support"],
  Kayn: ["ad", "assassin", "sustain", "mobile"],
  Kennen: ["ap", "heavy_cc", "mobile"],
  "Kha'Zix": ["ad", "assassin", "burst", "mobile"],
  Kindred: ["ad", "mobile"],
  Kled: ["frontline", "high_hp", "ad", "mobile"],
  "Kog'Maw": ["ad", "ap", "poke"],
  "K'Sante": ["tank", "frontline", "heavy_cc", "mobile"],
  LeBlanc: ["ap", "assassin", "burst", "mobile"],
  "Lee Sin": ["frontline", "ad", "burst", "mobile"],
  Leona: ["tank", "frontline", "heavy_cc", "support"],
  Lillia: ["ap", "heavy_cc", "mobile"],
  Lissandra: ["ap", "burst", "heavy_cc"],
  Lucian: ["ad", "burst", "mobile"],
  Lulu: ["support", "shielding", "heavy_cc"],
  Lux: ["ap", "burst", "heavy_cc", "poke", "support"],
  Malphite: ["tank", "frontline", "heavy_cc", "ap"],
  Malzahar: ["ap", "heavy_cc", "poke"],
  Maokai: ["tank", "frontline", "heavy_cc", "support", "healing"],
  "Master Yi": ["ad", "assassin", "sustain", "mobile"],
  Mel: ["ap", "burst", "poke"],
  Milio: ["support", "healing", "shielding"],
  "Miss Fortune": ["ad", "burst", "poke"],
  Wukong: ["frontline", "heavy_cc", "ad", "mobile"],
  Mordekaiser: ["tank", "frontline", "ap", "sustain"],
  Morgana: ["ap", "heavy_cc", "support"],
  Naafiri: ["ad", "assassin", "burst", "mobile"],
  Nami: ["support", "healing", "heavy_cc", "ap"],
  Nasus: ["tank", "frontline", "high_hp", "sustain", "ad"],
  Nautilus: ["tank", "frontline", "heavy_cc", "support"],
  Neeko: ["ap", "burst", "heavy_cc"],
  Nidalee: ["ap", "poke", "healing", "mobile"],
  Nilah: ["ad", "sustain", "mobile"],
  Nocturne: ["ad", "assassin", "burst", "mobile"],
  "Nunu & Willump": ["tank", "frontline", "heavy_cc", "ap"],
  Olaf: ["frontline", "sustain", "ad"],
  Orianna: ["ap", "shielding", "heavy_cc", "poke"],
  Ornn: ["tank", "frontline", "heavy_cc"],
  Pantheon: ["frontline", "ad", "burst", "heavy_cc"],
  Poppy: ["tank", "frontline", "heavy_cc"],
  Pyke: ["ad", "assassin", "heavy_cc", "support"],
  Qiyana: ["ad", "assassin", "burst", "heavy_cc", "mobile"],
  Quinn: ["ad", "assassin", "mobile"],
  Rakan: ["support", "healing", "heavy_cc", "mobile"],
  Rammus: ["tank", "frontline", "heavy_cc"],
  "Rek'Sai": ["frontline", "ad", "burst", "mobile"],
  Rell: ["tank", "frontline", "heavy_cc", "support"],
  "Renata Glasc": ["support", "shielding", "heavy_cc"],
  Renekton: ["frontline", "sustain", "ad"],
  Rengar: ["ad", "assassin", "burst", "mobile"],
  Riven: ["ad", "burst", "mobile"],
  Rumble: ["ap", "frontline"],
  Ryze: ["ap", "heavy_cc"],
  Samira: ["ad", "burst", "mobile"],
  Sejuani: ["tank", "frontline", "heavy_cc"],
  Senna: ["support", "healing", "ad", "poke"],
  Seraphine: ["support", "healing", "shielding", "heavy_cc", "ap"],
  Sett: ["frontline", "high_hp", "ad", "heavy_cc"],
  Shaco: ["ad", "ap", "assassin", "burst", "mobile"],
  Shen: ["tank", "frontline", "shielding", "support"],
  Shyvana: ["tank", "frontline", "ap", "ad"],
  Singed: ["tank", "frontline", "ap"],
  Sion: ["tank", "frontline", "high_hp", "heavy_cc"],
  Sivir: ["ad", "poke"],
  Skarner: ["tank", "frontline", "heavy_cc"],
  Smolder: ["ad", "ap", "poke", "mobile"],
  Sona: ["support", "healing", "shielding", "heavy_cc"],
  Soraka: ["healing", "support"],
  Swain: ["ap", "frontline", "sustain", "heavy_cc"],
  Sylas: ["ap", "burst", "sustain", "mobile"],
  Syndra: ["ap", "burst", "heavy_cc"],
  "Tahm Kench": ["tank", "frontline", "high_hp", "support"],
  Taliyah: ["ap", "heavy_cc", "poke"],
  Talon: ["ad", "assassin", "burst", "mobile"],
  Taric: ["support", "healing", "shielding", "heavy_cc"],
  Teemo: ["ap", "poke", "mobile"],
  Thresh: ["support", "heavy_cc", "tank"],
  Tristana: ["ad", "burst", "mobile"],
  Trundle: ["tank", "frontline", "sustain", "ad"],
  Tryndamere: ["ad", "sustain", "mobile"],
  "Twisted Fate": ["ap", "heavy_cc"],
  Twitch: ["ad", "assassin"],
  Udyr: ["tank", "frontline", "sustain", "heavy_cc", "mobile"],
  Urgot: ["tank", "frontline", "ad"],
  Varus: ["ad", "ap", "poke", "heavy_cc"],
  Vayne: ["ad", "mobile"],
  Veigar: ["ap", "burst", "heavy_cc"],
  "Vel'Koz": ["ap", "burst", "poke", "heavy_cc"],
  Vex: ["ap", "burst", "heavy_cc"],
  Vi: ["frontline", "ad", "burst", "heavy_cc", "mobile"],
  Viego: ["ad", "assassin", "sustain", "mobile"],
  Viktor: ["ap", "burst", "poke"],
  Vladimir: ["ap", "sustain", "burst"],
  Volibear: ["tank", "frontline", "sustain", "heavy_cc", "ad"],
  Warwick: ["frontline", "sustain", "heavy_cc", "ad"],
  Xayah: ["ad", "heavy_cc"],
  Xerath: ["ap", "burst", "heavy_cc", "poke"],
  "Xin Zhao": ["frontline", "ad", "sustain", "mobile"],
  Yasuo: ["ad", "mobile"],
  Yone: ["ad", "burst", "mobile"],
  Yorick: ["frontline", "high_hp", "ad"],
  Yunara: ["ad", "ap", "poke"],
  Yuumi: ["support", "healing", "shielding"],
  Zaahen: ["frontline", "ad", "sustain", "mobile"],
  Zac: ["tank", "frontline", "heavy_cc", "sustain"],
  Zed: ["ad", "assassin", "burst", "mobile"],
  Zeri: ["ad", "mobile"],
  Ziggs: ["ap", "poke"],
  Zilean: ["support", "heavy_cc", "mobile"],
  Zoe: ["ap", "burst", "poke", "heavy_cc"],
  Zyra: ["ap", "poke", "heavy_cc", "support"],
};
