import type { RecommendationRule } from "./types";

export const recommendationRules: RecommendationRule[] = [
  {
    id: "anti_tank",
    requiredTags: ["tank"],
    recommendItem: "Liandrys",
    situationalItemCategory: "antiTank",
    score: 30,
    reason: "Enemy team contains tanks",
    compatibleChampionTags: ["ap", "ad"],
  },
  {
    id: "anti_heal",
    requiredTags: ["healing"],
    recommendItem: "Morello",
    situationalItemCategory: "antiHeal",
    score: 35,
    reason: "Enemy team has healing",
    compatibleChampionTags: ["ap", "ad"],
  },
  {
    id: "anti_burst",
    requiredTags: ["burst"],
    recommendItem: "Zhonyas",
    situationalItemCategory: "antiBurst",
    score: 30,
    reason: "Enemy team has burst damage",
    compatibleChampionTags: ["ap", "assassin"],
  },
  {
    id: "anti_ap",
    requiredTags: ["ap"],
    recommendItem: "MercuryTreads",
    situationalItemCategory: "antiAp",
    score: 25,
    reason: "Enemy team has magic damage threats",
    compatibleChampionTags: ["ad", "tank", "support", "frontline"],
  },
  {
    id: "anti_ad",
    requiredTags: ["ad"],
    recommendItem: "PlatedSteelcaps",
    situationalItemCategory: "antiAd",
    score: 25,
    reason: "Enemy team has physical damage threats",
    compatibleChampionTags: ["ap", "tank", "support"],
  },
  {
    id: "anti_cc",
    requiredTags: ["heavy_cc"],
    recommendItem: "QuicksilverSash",
    situationalItemCategory: "antiCc",
    score: 30,
    reason: "Enemy team has heavy crowd control",
    compatibleChampionTags: ["ad", "ap"],
  },
  {
    id: "anti_poke",
    requiredTags: ["poke"],
    recommendItem: "DoranShield",
    situationalItemCategory: "antiPoke",
    score: 20,
    reason: "Enemy team has poke pressure",
    compatibleChampionTags: ["tank", "frontline", "support"],
  },
];
